/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentation.roomAndaccessory.view;

import app.core.components.MaInternalFrame;
import presentation.booking.controller.Booking;
import presentation.booking.view.BookingFrame;
import presentation.roomAndaccessory.controller.Room;
import app.core.components.*;
import app.core.components.fonts.IBMPlexSansThaiFont;
import java.awt.Color;

/**
 *
 * @author poke
 */
public class EditRoomFrame extends MaInternalFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(EditRoomFrame.class.getName());

    /**
     * Creates new form EditRoomFrame
     */
    private Room room = null;
    private String id;
    private RoomFrame parent;

    public EditRoomFrame(RoomFrame parent) {
        this.parent = parent;
        initComponents();
        updateRender();
    }

    public EditRoomFrame(String id, RoomFrame parent) {
        this.parent = parent;
        room = Room.data.get(id);
        initComponents();
        updateRender();
        maLabel1.setText("รหัสห้อง : " + id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        maLabel1 = new app.core.components.MaLabel();
        maLabel2 = new app.core.components.MaLabel();
        maLabel3 = new app.core.components.MaLabel();
        maLabel3.setFont(IBMPlexSansThaiFont.medium(14f));
        roomname = new app.core.components.MaTextField();
        priceperhour = new app.core.components.MaTextField();
        maButton1 = new app.core.components.MaButton();

        setTitle("เเก้ไขห้อง");

        maLabel1.setText("+ เพิ่มห้องใหม่");
        maLabel1.setTextColor(Macolor.magreen);
        maLabel1.setFont(IBMPlexSansThaiFont.medium(16));

        maLabel2.setFont(IBMPlexSansThaiFont.medium(14f));
        maLabel2.setText("ชื่อห้อง");

        maLabel3.setText("ราคาต่อชั่วโมง");

        roomname.setArc(20);
        roomname.setPadding(10);
        roomname.setColumns(20);
        roomname.setFieldColor(Color.white);
        roomname.setBorderSize(1);
        roomname.setBorderColor(Macolor.textgrey);

        priceperhour.setArc(20);
        priceperhour.setPadding(10);
        priceperhour.setColumns(20);
        priceperhour.setFieldColor(Color.white);
        priceperhour.setBorderSize(1);
        priceperhour.setBorderColor(Macolor.textgrey);

        maButton1.setText("บันทึก");
        maButton1.setBorderColor(Macolor.trans);
        maButton1.setButtonColor(Macolor.magreen);
        maButton1.setTextColor(Color.white);
        maButton1.addActionListener(this::maButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(maButton1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(priceperhour,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 340,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(maLabel3,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(roomname,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 340,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addContainerGap(39, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(maLabel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(maLabel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(130, 295, Short.MAX_VALUE)))));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(maLabel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(maLabel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(roomname, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(maLabel3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(priceperhour, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(maButton1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(23, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void maButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_maButton1ActionPerformed
        // TODO add your handling code here:
        boolean isNew = (room == null);
        if (isNew) {
            room = new Room(null, "", 0);
        }

        Room.updateRoomData(room, roomname.getText(), priceperhour.getText());

        if (isNew) {
            Room.postRoom(room, logger);
        } else {
            Room.updateRoom(room, logger);
        }
        parent.updateRender();
        dispose();
    }// GEN-LAST:event_maButton1ActionPerformed

    public void updateRender() {
        if (room != null) {
            roomname.setText(room.getName());
            priceperhour.setText("" + room.getPricePerHour());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.core.components.MaButton maButton1;
    private app.core.components.MaLabel maLabel1;
    private app.core.components.MaLabel maLabel2;
    private app.core.components.MaLabel maLabel3;
    private app.core.components.MaTextField priceperhour;
    private app.core.components.MaTextField roomname;
    // End of variables declaration//GEN-END:variables
}
