/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentation.roomAndaccessory.view;

import app.core.components.MaInternalFrame;
import presentation.roomAndaccessory.controller.Accessory;
import app.core.components.*;
import app.core.components.fonts.IBMPlexSansThaiFont;
import java.awt.Color;
/**
 *
 * @author poke
 */
public class EditAccessoryFrame extends MaInternalFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditAccessoryFrame.class.getName());

    /**
     * Creates new form EditAccessory
     */
    private Accessory accessory = null;
    private String id;
    private RoomFrame parent;

    public EditAccessoryFrame(RoomFrame parent) {
        this.parent = parent;
        initComponents();
        updateRender();
    }

    public EditAccessoryFrame(String id, RoomFrame parent) {
        this.parent = parent;
        accessory = Accessory.data.get(id);
        System.out.println("name : " + accessory.getName());
        initComponents();
        updateRender();
        maLabel1.setText("อุปกรณ์ที่ : " + id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        maLabel1 = new app.core.components.MaLabel();
        maLabel2 = new app.core.components.MaLabel();
        maLabel2.setFont(IBMPlexSansThaiFont.medium(14f));
        maLabel3 = new app.core.components.MaLabel();
        accessoryName = new app.core.components.MaTextField();
        accessoryPricePerHour = new app.core.components.MaTextField();
        submitBtn = new app.core.components.MaButton();

        setResizable(true);
        setTitle("เเก้ไขอุปปกรณ์");

        maLabel1.setText("+ เพิ่มอุปกรณ์ใหม่");
        maLabel1.setTextColor(Macolor.magreen);
        maLabel1.setFont(IBMPlexSansThaiFont.medium(16));

        maLabel2.setText("ชื่ออุปกรณ์");

        maLabel3.setFont(IBMPlexSansThaiFont.medium(14f));
        maLabel3.setText("ราคาต่อชั่วโมง");

        accessoryName.setArc(20);
        accessoryName.setPadding(10);
        accessoryName.setColumns(20);
        accessoryName.setFieldColor(Color.white);
        accessoryName.setBorderSize(1);
        accessoryName.setBorderColor(Macolor.textgrey);
        accessoryName.addActionListener(this::accessoryNameActionPerformed);

        accessoryPricePerHour.setArc(20);
        accessoryPricePerHour.setPadding(10);
        accessoryPricePerHour.setColumns(20);
        accessoryPricePerHour.setFieldColor(Color.white);
        accessoryPricePerHour.setBorderSize(1);
        accessoryPricePerHour.setBorderColor(Macolor.textgrey);

        submitBtn.setText("บันทึก");
        submitBtn.setBorderColor(Macolor.trans);
        submitBtn.setButtonColor(Macolor.magreen);
        submitBtn.setTextColor(Color.white);
        submitBtn.addActionListener(this::submitBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(accessoryPricePerHour, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(maLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(maLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(maLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(accessoryName, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(maLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(maLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(accessoryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(maLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(accessoryPricePerHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accessoryNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accessoryNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accessoryNameActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        boolean isNew = (accessory == null);
        if (isNew) {
            accessory = new Accessory(null, "", 0);
        }

        Accessory.updateAccessoryData(accessory, accessoryName.getText(), accessoryPricePerHour.getText());

        if (isNew) {
            Accessory.postAccessory(accessory, logger);
        } else {
            Accessory.updateAccessory(accessory, logger);
        }
        parent.updateRender();
        dispose();

    }//GEN-LAST:event_submitBtnActionPerformed
    public void updateRender() {
        if (accessory != null) {
            System.out.println(accessory);
            System.out.println("name : " + accessory.getName());
            accessoryName.setText(accessory.getName());
            accessoryPricePerHour.setText("" + accessory.getPricePerHour());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.core.components.MaTextField accessoryName;
    private app.core.components.MaTextField accessoryPricePerHour;
    private app.core.components.MaLabel maLabel1;
    private app.core.components.MaLabel maLabel2;
    private app.core.components.MaLabel maLabel3;
    private app.core.components.MaButton submitBtn;
    // End of variables declaration//GEN-END:variables
}
