/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentation.roomAndaccessory.view;

/**
 *
 * @author poke
 */
import presentation.booking.view.BookingTableFrame;
import presentation.booking.view.BookingFrame;
import presentation.auth.view.SignInFrame;
import app.core.components.Macolor;
import app.core.components.MaFrame;
import app.core.components.MaInternalFrame;
import app.core.components.MaTable;
import app.core.components.fonts.IBMPlexSansThaiFont;
import model.client.PocketBaseClient;
import model.client.PocketBaseClient.PBResponse;
import model.session.SessionManager;
import java.awt.Color;
import java.awt.*;
import java.awt.FlowLayout;
import java.awt.Image;
import java.awt.TextField;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.*;
import javax.swing.ImageIcon;
import javax.swing.table.*;
import java.util.*;
import java.awt.image.*;
import java.time.LocalDate;
import presentation.booking.controller.Booking;
import app.MainFrame;
import presentation.roomAndaccessory.controller.Accessory;
import presentation.roomAndaccessory.controller.Room;

public class RoomFrame extends MaInternalFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(RoomFrame.class.getName());

    private int selectedRoomId = -1;
    private int selectedAccessoryId = -1;

    /**
     * Creates new form RoomFrame
     */
    public RoomFrame() {
        initComponents();
        loadData();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navLabel1 = new app.core.components.NavLabel();
        navLabel2 = new app.core.components.NavLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        maTable1 = new app.core.components.MaTable();
        maTable2 = new app.core.components.MaTable();
        navLabel3 = new app.core.components.NavLabel();
        maLabel1 = new app.core.components.MaLabel();
        maLabel2 = new app.core.components.MaLabel();
        addRoomBtn = new app.core.components.MaButton();
        editRoomBtn = new app.core.components.MaButton();
        delRoomBtn = new app.core.components.MaButton();
        addAcces = new app.core.components.MaButton();
        maButton5 = new app.core.components.MaButton();
        delAccessoryBtn = new app.core.components.MaButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
                jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE));
        jInternalFrame1Layout.setVerticalGroup(
                jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE));

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("จัดการห้องเเละอุปกรณ์");

        navLabel3.setExtraText("จัดการห้องเเละอุปกรณ์");

        maLabel1.setText("ห้องทั้งหมด");
        maLabel1.setFont(IBMPlexSansThaiFont.medium(16f));

        maLabel2.setText("อุปกรณ์ทั้งหมด");
        maLabel2.setFont(IBMPlexSansThaiFont.medium(16f));

        addRoomBtn.setBorderColor(Macolor.trans);
        addRoomBtn.setTextColor(Macolor.magreen);
        addRoomBtn.setButtonColor(Macolor.trans);
        addRoomBtn.setText("+");
        addRoomBtn.addActionListener(this::addRoomBtnActionPerformed);

        editRoomBtn.setText("Edit");
        editRoomBtn.setButtonColor(Macolor.trans);
        editRoomBtn.setBorderColor(Macolor.trans);
        editRoomBtn.setTextColor(Macolor.mablue);
        editRoomBtn.addActionListener(this::editRoomBtnActionPerformed);

        delRoomBtn.setText("Del");
        delRoomBtn.setButtonColor(Macolor.trans);
        delRoomBtn.setBorderColor(Macolor.trans);
        delRoomBtn.setTextColor(Macolor.mared);
        delRoomBtn.addActionListener(this::delRoomBtnActionPerformed);

        addAcces.setText("+");
        addAcces.setBorderColor(Macolor.trans);
        addAcces.setTextColor(Macolor.magreen);
        addAcces.setButtonColor(Macolor.trans);
        addAcces.addActionListener(this::addAccesActionPerformed);

        maButton5.setText("Edit");
        maButton5.setButtonColor(Macolor.trans);
        maButton5.setBorderColor(Macolor.trans);
        maButton5.setTextColor(Macolor.mablue);
        maButton5.addActionListener(this::maButton5ActionPerformed);

        delAccessoryBtn.setButtonColor(Macolor.trans);
        delAccessoryBtn.setBorderColor(Macolor.trans);
        delAccessoryBtn.setTextColor(Macolor.mared);
        delAccessoryBtn.setText("Del");
        delAccessoryBtn.addActionListener(this::delAccessoryBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(maLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addComponent(maTable1,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 534,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(editRoomBtn,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                0, Short.MAX_VALUE)
                                                                        .addGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                layout.createSequentialGroup()
                                                                                        .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                2, Short.MAX_VALUE)
                                                                                        .addComponent(delRoomBtn,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                64,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addComponent(addRoomBtn,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(maLabel2,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        467,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                        67,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addComponent(maTable2,
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                534,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                .addComponent(addAcces,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        64,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addComponent(maButton5,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                0, Short.MAX_VALUE)
                                                                        .addComponent(delAccessoryBtn,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                0, Short.MAX_VALUE))))
                                                .addGap(29, 29, 29))))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(navLabel3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(navLabel3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(maLabel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(addRoomBtn, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(editRoomBtn, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(delRoomBtn, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(maTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 175,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addComponent(maLabel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(26, 26, 26)
                                                .addComponent(maTable2, javax.swing.GroupLayout.PREFERRED_SIZE, 182,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(addAcces, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(maButton5, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(delAccessoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(69, 69, 69)))
                                .addGap(69, 69, 69)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void delRoomBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_delRoomBtnActionPerformed
        // TODO add your handling code here:
        int tableselectedRow = maTable1.getSelectedRow();
        // System.out.println(tableselectedRow);
        if (tableselectedRow >= 0) {
            ArrayList<String> Roomkey = new ArrayList<>(Room.data.keySet());
            String key = Roomkey.get(tableselectedRow);
            Room.deleteRoom(key, logger);
            updateRender();
        }
    }// GEN-LAST:event_delRoomBtnActionPerformed

    private void editRoomBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_editRoomBtnActionPerformed
        // TODO add your handling code here:
        int tableselectedRow = maTable1.getSelectedRow();
        System.out.println(tableselectedRow);
        if (tableselectedRow >= 0) {
            ArrayList<String> roomKeys = new ArrayList<>(Room.data.keySet());
            String key = roomKeys.get(tableselectedRow);
            Room updateRoom = Room.data.get(key);
            updateRoom.getId();
            MainFrame.getInstance().openInternalFrame(new EditRoomFrame(updateRoom.getId(), this));
        }
    }// GEN-LAST:event_editRoomBtnActionPerformed

    private void addRoomBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addRoomBtnActionPerformed
        // TODO add your handling code here:
        MainFrame.getInstance().openInternalFrame(new EditRoomFrame(this));
    }// GEN-LAST:event_addRoomBtnActionPerformed

    private void maButton5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_maButton5ActionPerformed
        // TODO add your handling code here:
        int tableselectedRow = maTable2.getSelectedRow();
        System.out.println(tableselectedRow);
        if (tableselectedRow >= 0) {
            ArrayList<String> accessKeys = new ArrayList<>(Accessory.data.keySet());
            String key = accessKeys.get(tableselectedRow);
            Accessory updateAccessory = Accessory.data.get(key);
            updateAccessory.getId();
            MainFrame.getInstance().openInternalFrame(new EditAccessoryFrame(updateAccessory.getId(), this));
        }
    }// GEN-LAST:event_maButton5ActionPerformed

    private void delAccessoryBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_delAccessoryBtnActionPerformed
        // TODO add your handling code here:
        int tableselectedRow = maTable2.getSelectedRow();
        // System.out.println(tableselectedRow);
        if (tableselectedRow >= 0) {
            ArrayList<String> accessorykey = new ArrayList<>(Accessory.data.keySet());
            String key = accessorykey.get(tableselectedRow);
            Accessory.deleteAccessory(key, logger);
            updateRender();
        }
    }// GEN-LAST:event_delAccessoryBtnActionPerformed

    private void addAccesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addAccesActionPerformed
        // TODO add your handling code here:
        MainFrame.getInstance().openInternalFrame(new EditAccessoryFrame(this));
    }// GEN-LAST:event_addAccesActionPerformed

    /**
     * @param args the command line arguments
     */
    private void loadData() {
        Room.loadRooms(logger);
        Accessory.loadAccessories(logger);
        updateRender();
    }

    public void updateRender() {
        ArrayList<String> columns = new ArrayList<>();
        columns.add("Room Name");
        columns.add("Price / Hour");

        ArrayList<Object[]> rows = new ArrayList<>();

        for (String key : Room.data.keySet()) {
            Room r = Room.data.get(key);

            String roomName = r.getName();
            double price = r.getPricePerHour();

            rows.add(new Object[] {
                    roomName,
                    price
            });
        }

        maTable1.updateView(columns, rows);

        ArrayList<String> columns1 = new ArrayList<>();
        columns1.add("Accessory Name");
        columns1.add("Price / Hour");

        ArrayList<Object[]> rows1 = new ArrayList<>();

        for (String key : Accessory.data.keySet()) {
            Accessory r = Accessory.data.get(key);

            String roomName = r.getName();
            double price = r.getPricePerHour();

            rows1.add(new Object[] {
                    roomName,
                    price
            });
        }

        maTable2.updateView(columns1, rows1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.core.components.MaButton addAcces;
    private app.core.components.MaButton addRoomBtn;
    private app.core.components.MaButton delAccessoryBtn;
    private app.core.components.MaButton delRoomBtn;
    private app.core.components.MaButton editRoomBtn;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private app.core.components.MaButton maButton5;
    private app.core.components.MaLabel maLabel1;
    private app.core.components.MaLabel maLabel2;
    private app.core.components.MaTable maTable1;
    private app.core.components.MaTable maTable2;
    private app.core.components.NavLabel navLabel1;
    private app.core.components.NavLabel navLabel2;
    private app.core.components.NavLabel navLabel3;
    // End of variables declaration//GEN-END:variables
}
