/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentation.booking.view;

/**
 *
 * @author poke
 */
import app.core.components.Macolor;
import app.core.components.MaFrame;
import app.core.components.MaTextField;
import app.core.components.fonts.IBMPlexSansThaiFont;
import model.client.PocketBaseClient;
import model.client.PocketBaseClient.PBResponse;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Image;
import java.awt.TextField;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.*;
import javax.swing.ImageIcon;
import presentation.booking.controller.Booking;

public class BookingFrame extends MaFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BookingFrame.class.getName());

    private int selectedBookingId = -1;

    /**
     * Creates new form BookingFrame
     */
    public BookingFrame() {
        initComponents();
        updateRender();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navLabel = new app.core.components.NavLabel();
        navLabel.setExtraText("จัดการการจอง");
        AddBtn = new app.core.components.MaButton();
        maTable1 = new app.core.components.MaTable();
        updateBtn = new app.core.components.MaButton();
        deleteBtn = new app.core.components.MaButton();
        maPanel1 = new app.core.components.MaPanel();
        maScrollPane1 = new app.core.components.MaScrollPane();
        maTextArea1 = new app.core.components.MaTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("จัดการการจอง");

        AddBtn.setBorderColor(Macolor.magreen);
        AddBtn.setTextColor(Macolor.magreen);
        AddBtn.setButtonColor(Color.white);
        AddBtn.setArc(35);
        AddBtn.setText("+ เพิ่มข้อมูล");
        AddBtn.addActionListener(this::AddBtnActionPerformed);

        updateBtn.setButtonColor(Color.white);
        updateBtn.setBorderColor(Macolor.mablue);
        updateBtn.setTextColor(Macolor.mablue);
        updateBtn.setArc(35);
        updateBtn.setText("เเก้ไขข้อมูลที่เลือก");
        updateBtn.addActionListener(this::updateBtnActionPerformed);

        deleteBtn.setButtonColor(Color.white);
        deleteBtn.setBorderColor(Macolor.mared);
        deleteBtn.setTextColor(Macolor.mared);
        deleteBtn.setArc(35);
        deleteBtn.setText("ลบข้อมูลที่เลือก");
        deleteBtn.addActionListener(this::deleteBtnActionPerformed);

        maPanel1.setBackground(Color.white);
        maPanel1.setBorderColor(Macolor.magreen);

        maScrollPane1.setScrollX(false);
        maScrollPane1.scrollToTop();

        maTextArea1.setColumns(20);
        maTextArea1.setRows(5);
        maTextArea1.setText("วิธีการใช้งาน\n** วิธีการเพิ่มข้อมูล**\n\nกดปุ่ม “+ เพิ่มข้อมูล”\n1. ระบบจะเปิดฟอร์มให้กรอกข้อมูล (ขึ้นอยู่กับการออกแบบระบบ)\n2.กรอกข้อมูลให้ครบในแต่ละคอลัมน์\n3.กดยืนยันเพื่อบันทึกข้อมูล\n4.ข้อมูลใหม่จะแสดงในตารางทันที\n\n*หมายเหตุ: ควรตรวจสอบความถูกต้องก่อนบันทึก\n\n\n** วิธีการลบข้อมูล **\n\n1.คลิกเลือกแถวข้อมูลที่ต้องการลบ\n2.กดปุ่ม “ลบข้อมูลที่เลือก”\n\n* คำเตือน: การลบข้อมูลไม่สามารถกู้คืนได้ ควรตรวจสอบก่อนลบทุกครั้ง");
        maTextArea1.setTextColor(Macolor.magreen);
        maTextArea1.setBackground(Color.white);
        maTextArea1.setFont(IBMPlexSansThaiFont.light(12f));
        maTextArea1.setEditable(false);
        maTextArea1.setCaretPosition(0);
        maScrollPane1.setViewportView(maTextArea1);

        javax.swing.GroupLayout maPanel1Layout = new javax.swing.GroupLayout(maPanel1);
        maPanel1.setLayout(maPanel1Layout);
        maPanel1Layout.setHorizontalGroup(
            maPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 256, Short.MAX_VALUE)
            .addGroup(maPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(maPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(maScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        maPanel1Layout.setVerticalGroup(
            maPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 364, Short.MAX_VALUE)
            .addGroup(maPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(maPanel1Layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(maScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(10, 10, 10)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(navLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(maPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(maTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(navLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        // TODO add your handling code here:
        new EditBookingFrame(this).setVisible(true);
    }//GEN-LAST:event_AddBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        int tableselectedRow = maTable1.getSelectedRow();
        System.out.println(tableselectedRow);
        if (tableselectedRow >= 0) {
            ArrayList<String> bookingKeys = new ArrayList<>(Booking.data.keySet());
            String key = bookingKeys.get(tableselectedRow);
            Booking updateBooking = Booking.data.get(key);
            updateBooking.getId();
            new EditBookingFrame(updateBooking.getId(),this).setVisible(true);
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int tableselectedRow = maTable1.getSelectedRow();
        System.out.println(tableselectedRow);
        if (tableselectedRow >= 0) {
            ArrayList<String> bookingKeys = new ArrayList<>(Booking.data.keySet());
            String key = bookingKeys.get(tableselectedRow);
            Booking.data.remove(key);
            updateRender();
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    public void updateRender() {
        ArrayList<String> columns = new ArrayList<>();
        columns.add("Room Name");
        columns.add("Customer Name");
        columns.add("Check In");
        columns.add("Check Out");

        ArrayList<Object[]> rows = new ArrayList<>();
        for (String key : Booking.data.keySet()) {
            Booking b = Booking.data.get(key);

            String customerName = b.getCustomer();
            String checkIn = b.getCheckIn();
            String checkOut = b.getCheckout();
            String roomName = b.getRoom();

            rows.add(new Object[]{
                roomName,
                customerName,
                checkIn,
                checkOut
            });
        }
        maTable1.updateView(columns, rows);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BookingFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.core.components.MaButton AddBtn;
    private app.core.components.MaButton deleteBtn;
    private app.core.components.MaPanel maPanel1;
    private app.core.components.MaScrollPane maScrollPane1;
    private app.core.components.MaTable maTable1;
    private app.core.components.MaTextArea maTextArea1;
    private app.core.components.NavLabel navLabel;
    private app.core.components.MaButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
