/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentation.booking.view;

/**
 *
 * @author poke
 */
import app.core.components.Macolor;
import app.core.components.MaFrame;
import app.core.components.MaInternalFrame;
import app.core.components.MaTextField;
import app.core.components.fonts.IBMPlexSansThaiFont;
import model.client.PocketBaseClient;
import model.client.PocketBaseClient.PBResponse;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Image;
import java.awt.TextField;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.*;
import javax.swing.ImageIcon;
import model.session.SessionManager;
import model.utils.TimeUtils;
import java.time.Instant;
import java.time.ZoneId;
import java.time.ZoneOffset;
import java.util.Map;
import presentation.roomAndaccessory.controller.Room;

public class BookingTableFrame extends MaInternalFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(BookingTableFrame.class.getName());

    private PocketBaseClient pb = SessionManager.pb;
    private PBResponse pbClient;

    /**
     * Creates new form BookingTable
     */
    public BookingTableFrame() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navLabel1 = new app.core.components.NavLabel();
        jTextField1 = new javax.swing.JTextField();
        dateLabel = new app.core.components.MaLabel();
        maTable1 = new app.core.components.MaTable();
        bookingCalendar = new app.core.components.MaBookingCalendar();
        navLabel2 = new app.core.components.NavLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ตารางการจอง");

        dateLabel.setText("** โปรดเลือกวันที่ **");

        maTable1.updateView(new ArrayList<>(), new ArrayList<>());

        navLabel2.setExtraText("ตารางการจอง");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(maTable1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 562,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(navLabel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addGap(19, 19, 19)
                                                        .addComponent(bookingCalendar,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 562,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(97, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(navLabel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bookingCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 303,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(maTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 183,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(58, Short.MAX_VALUE)));

        bookingCalendar.addDateSelectionListener(this::bookingCalendar1ActionPerformed);
        bookingCalendar.setBorderColor(Macolor.magreen);
        bookingCalendar.setArc(10);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookingCalendar1ActionPerformed(LocalDate selectedDate) {
        System.out.println("User selected: " + "\t" + selectedDate);
        dateLabel.setText("ข้อมูลการจอง ณ วันที่ :" + selectedDate);

        String[] utcRange = TimeUtils.convertDateToUtcRange(selectedDate, ZoneId.of("Asia/Bangkok"));
        String startUtc = utcRange[0]; // e.g., "2026-03-20T17:00:00Z"
        String endUtc = utcRange[1]; // e.g., "2026-03-21T17:00:00Z"
        if (!pb.isAuthenticated()) {
            System.out.println(pb.getAuthToken());
            return;
        }
        String filter = "checkIn_time <= '" + endUtc + "' && checkIn_time >= '" + startUtc + "'";
        Map<String, String> params = Map.of("filter", filter);
        try {
            PBResponse res = pb.getRecords("java_book", params);

            if (!res.isOk()) {
                logger.warning("Failed to load bookings: " + res.getStatusCode());
                return;
            }

            ArrayList<String> columns = new ArrayList<>();
            columns.add("Room Name");
            columns.add("Customer Name");
            columns.add("Check In");
            columns.add("Time Slot");

            ArrayList<Object[]> rows = new ArrayList<>();

            List<String> items = res.getItems();

            if (items.isEmpty()) {
                dateLabel.setText("ไม่มีคิวในวันนี้");
                rows.add(new Object[] { "-", "-", "-", "-" });
            }

            for (String item : items) {

                String customerName = PocketBaseClient.extractJsonString(item, "customer_name");
                String checkIn = PocketBaseClient.extractJsonString(item, "checkIn_time");
                String timeSlot = PocketBaseClient.extractJsonString(item, "time_slot");
                String roomId = PocketBaseClient.extractJsonString(item, "room");
                String roomName = Room.data.get(roomId).getName();

                rows.add(new Object[] {
                        roomName,
                        customerName,
                        checkIn,
                        timeSlot,
                });
            }

            maTable1.updateView(columns, rows);

        } catch (java.io.IOException | InterruptedException ex

        ) {
            logger.log(java.util.logging.Level.SEVERE, "Failed to load bookings", ex);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BookingTableFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.core.components.MaBookingCalendar bookingCalendar;
    private app.core.components.MaLabel dateLabel;
    private javax.swing.JTextField jTextField1;
    private app.core.components.MaTable maTable1;
    private app.core.components.NavLabel navLabel1;
    private app.core.components.NavLabel navLabel2;
    // End of variables declaration//GEN-END:variables
}
