package presentation.booking.view;

import app.core.components.Macolor;
import app.core.components.MaFrame;
import app.core.components.MaFrame;
import app.core.components.MaTable;
import app.core.components.fonts.IBMPlexSansThaiFont;
import model.client.PocketBaseClient;
import model.client.PocketBaseClient.PBResponse;
import model.session.SessionManager;
import java.awt.Color;
import java.awt.*;
import java.awt.FlowLayout;
import java.awt.Image;
import java.awt.TextField;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.*;
import javax.swing.ImageIcon;
import javax.swing.table.*;
import java.util.*;
import java.awt.image.*;
public class EditBookingFrame extends MaFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditBookingFrame.class.getName());

    /**
     * Creates new form AddBookingFrame
     */
    public EditBookingFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        maComboBox8 = new app.core.components.MaComboBox();
        maComboBox11 = new app.core.components.MaComboBox();
        maComboBox9 = new app.core.components.MaComboBox();
        maComboBox10 = new app.core.components.MaComboBox();
        maComboBox7 = new app.core.components.MaComboBox();
        maLabel3 = new app.core.components.MaLabel();
        maComboBox2 = new app.core.components.MaComboBox();
        maLabel2 = new app.core.components.MaLabel();
        maTextField1 = new app.core.components.MaTextField();
        maLabel4 = new app.core.components.MaLabel();
        maComboBox1 = new app.core.components.MaComboBox();
        maComboBox3 = new app.core.components.MaComboBox();
        maComboBox4 = new app.core.components.MaComboBox();
        maLabel7 = new app.core.components.MaLabel();
        maComboBox5 = new app.core.components.MaComboBox();
        maComboBox17 = new app.core.components.MaComboBox();
        maLabel8 = new app.core.components.MaLabel();
        maComboBox6 = new app.core.components.MaComboBox();
        maComboBox16 = new app.core.components.MaComboBox();
        maComboBox19 = new app.core.components.MaComboBox();
        maLabel9 = new app.core.components.MaLabel();
        maComboBox20 = new app.core.components.MaComboBox();
        maComboBox21 = new app.core.components.MaComboBox();
        maLabel1 = new app.core.components.MaLabel();
        maButton1 = new app.core.components.MaButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        maLabel3.setText("ห้อง");
        maLabel3.setFont(IBMPlexSansThaiFont.medium(16f));

        maComboBox2.getArrow().setBackground(Macolor.trans);
        maComboBox2.getArrow().setBorderColor(Macolor.trans);
        maComboBox2.getArrow().setTextColor(Macolor.magreen);

        maLabel2.setText("ชื่อลูกค้า");
        maLabel2.setFont(IBMPlexSansThaiFont.medium(16f));

        maTextField1.setPadding(10);
        maTextField1.setColumns(20);
        maTextField1.addActionListener(this::maTextField1ActionPerformed);

        maLabel4.setText("วันที่เข้า");
        maLabel4.setFont(IBMPlexSansThaiFont.medium(14f));

        maComboBox1.getArrow().setBackground(Macolor.trans);
        maComboBox1.getArrow().setBorderColor(Macolor.trans);
        maComboBox1.getArrow().setTextColor(Macolor.magreen);

        maComboBox3.getArrow().setBackground(Macolor.trans);
        maComboBox3.getArrow().setBorderColor(Macolor.trans);
        maComboBox3.getArrow().setTextColor(Macolor.magreen);

        maComboBox4.getArrow().setBackground(Macolor.trans);
        maComboBox4.getArrow().setBorderColor(Macolor.trans);
        maComboBox4.getArrow().setTextColor(Macolor.magreen);

        maLabel7.setText("เวลาที่เข้า");
        maLabel7.setFont(IBMPlexSansThaiFont.medium(14f));

        maComboBox5.getArrow().setBackground(Macolor.trans);
        maComboBox5.getArrow().setBorderColor(Macolor.trans);
        maComboBox5.getArrow().setTextColor(Macolor.magreen);

        maComboBox17.getArrow().setBackground(Macolor.trans);
        maComboBox17.getArrow().setBorderColor(Macolor.trans);
        maComboBox17.getArrow().setTextColor(Macolor.magreen);

        maLabel8.setText("วันที่ออก");
        maLabel8.setFont(IBMPlexSansThaiFont.medium(14f));

        maComboBox6.getArrow().setBackground(Macolor.trans);
        maComboBox6.getArrow().setBorderColor(Macolor.trans);
        maComboBox6.getArrow().setTextColor(Macolor.magreen);

        maComboBox16.getArrow().setBackground(Macolor.trans);
        maComboBox16.getArrow().setBorderColor(Macolor.trans);
        maComboBox16.getArrow().setTextColor(Macolor.magreen);

        maComboBox19.getArrow().setBackground(Macolor.trans);
        maComboBox19.getArrow().setBorderColor(Macolor.trans);
        maComboBox19.getArrow().setTextColor(Macolor.magreen);

        maLabel9.setText("เวลาที่ออก");
        maLabel9.setFont(IBMPlexSansThaiFont.medium(14f));

        maComboBox20.getArrow().setBackground(Macolor.trans);
        maComboBox20.getArrow().setBorderColor(Macolor.trans);
        maComboBox20.getArrow().setTextColor(Macolor.magreen);

        maComboBox21.getArrow().setBackground(Macolor.trans);
        maComboBox21.getArrow().setBorderColor(Macolor.trans);
        maComboBox21.getArrow().setTextColor(Macolor.magreen);

        maLabel1.setText("+ ห้องใหม่");
        maLabel1.setTextColor(Macolor.magreen);
        maLabel1.setFont(IBMPlexSansThaiFont.bold(24f));

        maButton1.setText("บันทึกข้อมูล");
        maButton1.setButtonColor(Macolor.magreen);
        maButton1.setBorderColor(Macolor.trans);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(maLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(maComboBox2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(maComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(maComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(maComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(maComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(maComboBox16, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(15, 15, 15)
                                        .addComponent(maComboBox19, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(maLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(maLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(maLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(maComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(maComboBox17, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(maComboBox20, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(maComboBox21, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(maButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(maLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(maLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(maLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(maTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(maLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(maLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maComboBox17, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(maLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maComboBox19, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maComboBox16, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(maLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maComboBox20, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maComboBox21, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(maButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void maTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EditBookingFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.core.components.MaButton maButton1;
    private app.core.components.MaComboBox maComboBox1;
    private app.core.components.MaComboBox maComboBox10;
    private app.core.components.MaComboBox maComboBox11;
    private app.core.components.MaComboBox maComboBox16;
    private app.core.components.MaComboBox maComboBox17;
    private app.core.components.MaComboBox maComboBox19;
    private app.core.components.MaComboBox maComboBox2;
    private app.core.components.MaComboBox maComboBox20;
    private app.core.components.MaComboBox maComboBox21;
    private app.core.components.MaComboBox maComboBox3;
    private app.core.components.MaComboBox maComboBox4;
    private app.core.components.MaComboBox maComboBox5;
    private app.core.components.MaComboBox maComboBox6;
    private app.core.components.MaComboBox maComboBox7;
    private app.core.components.MaComboBox maComboBox8;
    private app.core.components.MaComboBox maComboBox9;
    private app.core.components.MaLabel maLabel1;
    private app.core.components.MaLabel maLabel2;
    private app.core.components.MaLabel maLabel3;
    private app.core.components.MaLabel maLabel4;
    private app.core.components.MaLabel maLabel7;
    private app.core.components.MaLabel maLabel8;
    private app.core.components.MaLabel maLabel9;
    private app.core.components.MaTextField maTextField1;
    // End of variables declaration//GEN-END:variables
}
