package presentation.booking.view;

import app.core.components.Macolor;
import app.core.components.MaFrame;
import app.core.components.MaFrame;
import app.core.components.MaInternalFrame;
import app.core.components.MaOptionPane;
import app.core.components.MaTable;
import app.core.components.fonts.IBMPlexSansThaiFont;
import model.client.PocketBaseClient;
import model.client.PocketBaseClient.PBResponse;
import model.session.SessionManager;
import java.awt.Color;
import java.awt.*;
import java.awt.FlowLayout;
import java.awt.Image;
import java.awt.TextField;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.*;
import javax.swing.ImageIcon;
import javax.swing.table.*;
import java.util.*;
import java.awt.image.*;
import java.time.LocalDateTime;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import model.utils.TimeUtils;
import presentation.booking.controller.Booking;
import presentation.roomAndaccessory.controller.Accessory;
import presentation.roomAndaccessory.controller.Room;

public class EditBookingFrame extends MaInternalFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(EditBookingFrame.class.getName());

    private Booking booking = null;
    private String id;
    private BookingFrame parent;
    private java.util.List<JCheckBox> accessoryCheckBoxes = new ArrayList<>();
    private javax.swing.JScrollPane accessoryScrollPane;

    /**
     * Creates new form AddBookingFrame
     */
    public EditBookingFrame(String id, BookingFrame parent) {
        this.parent = parent;
        booking = Booking.data.get(id);
        initComponents();
        updateRender();
        if (id.length() >= 8) {
            String newId = "";
            for (int i = 0; i < 8; i++) {
                newId += id.charAt(i);
            }
            id = newId;
        }
        maLabel1.setText("รหัสการจอง : " + id + "...");
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    public EditBookingFrame(BookingFrame parent) {
        this.parent = parent;
        initComponents();
        updateRender();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        maComboBox8 = new app.core.components.MaComboBox();
        maComboBox11 = new app.core.components.MaComboBox();
        maComboBox9 = new app.core.components.MaComboBox();
        maComboBox10 = new app.core.components.MaComboBox();
        maComboBox7 = new app.core.components.MaComboBox();
        maLabel3 = new app.core.components.MaLabel();
        roomComboBox = new app.core.components.MaComboBox();
        maLabel2 = new app.core.components.MaLabel();
        customerName = new app.core.components.MaTextField();
        maLabel4 = new app.core.components.MaLabel();
        CheckInMonthCombobox = new app.core.components.MaComboBox();
        CheckInDateCombobox = new app.core.components.MaComboBox();
        CheckInYearCombobox = new app.core.components.MaComboBox();
        maLabel7 = new app.core.components.MaLabel();
        CheckInTimeSlotCombobox = new app.core.components.MaComboBox();
        maLabel1 = new app.core.components.MaLabel();
        submitBtn = new app.core.components.MaButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        maLabel3.setText("ห้อง");
        maLabel3.setFont(IBMPlexSansThaiFont.medium(16f));

        roomComboBox.getArrow().setBackground(Macolor.trans);
        roomComboBox.getArrow().setBorderColor(Macolor.trans);
        roomComboBox.getArrow().setTextColor(Macolor.magreen);

        maLabel2.setText("ชื่อลูกค้า");
        maLabel2.setFont(IBMPlexSansThaiFont.medium(16f));

        customerName.setPadding(10);
        customerName.setColumns(20);
        customerName.addActionListener(this::customerNameActionPerformed);

        maLabel4.setText("วันที่เข้า");
        maLabel4.setFont(IBMPlexSansThaiFont.medium(14f));

        CheckInMonthCombobox.getArrow().setBackground(Macolor.trans);
        CheckInMonthCombobox.getArrow().setBorderColor(Macolor.trans);
        CheckInMonthCombobox.getArrow().setTextColor(Macolor.magreen);

        CheckInDateCombobox.getArrow().setBackground(Macolor.trans);
        CheckInDateCombobox.getArrow().setBorderColor(Macolor.trans);
        CheckInDateCombobox.getArrow().setTextColor(Macolor.magreen);

        CheckInYearCombobox.getArrow().setBackground(Macolor.trans);
        CheckInYearCombobox.getArrow().setBorderColor(Macolor.trans);
        CheckInYearCombobox.getArrow().setTextColor(Macolor.magreen);

        maLabel7.setText("เวลาที่เข้า");
        maLabel7.setFont(IBMPlexSansThaiFont.medium(14f));

        CheckInTimeSlotCombobox.getArrow().setBackground(Macolor.trans);
        CheckInTimeSlotCombobox.getArrow().setBorderColor(Macolor.trans);
        CheckInTimeSlotCombobox.getArrow().setTextColor(Macolor.magreen);

        maLabel1.setText("+ ห้องใหม่");
        maLabel1.setTextColor(Macolor.magreen);
        maLabel1.setFont(IBMPlexSansThaiFont.bold(24f));

        submitBtn.setText("บันทึกข้อมูล");
        submitBtn.setButtonColor(Macolor.magreen);
        submitBtn.setBorderColor(Macolor.trans);
        submitBtn.addActionListener(this::submitBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout
                                                .createSequentialGroup()
                                                .addGap(32, 32, 32)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(maLabel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(14, 14, 14)
                                                                .addComponent(maLabel3,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(roomComboBox,
                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 299,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(10, 10, 10)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(CheckInDateCombobox,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        82,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(CheckInMonthCombobox,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        96,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(12, 12, 12)
                                                                                .addComponent(CheckInYearCombobox,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        0, Short.MAX_VALUE))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(maLabel7,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                                        .addComponent(CheckInTimeSlotCombobox,
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)))
                                                        .addComponent(submitBtn, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout
                                                .createSequentialGroup()
                                                .addGap(42, 42, 42)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(customerName,
                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, 299,
                                                                Short.MAX_VALUE)
                                                        .addComponent(maLabel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(maLabel4, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(51, 51, 51)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(maLabel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(maLabel3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(roomComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 41,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(maLabel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(customerName, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(maLabel4, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CheckInDateCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(CheckInMonthCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(CheckInYearCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(maLabel7, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CheckInTimeSlotCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(47, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customerNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_customerNameActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_customerNameActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_submitBtnActionPerformed
        boolean isNew = (booking == null);
        if (isNew) {
            booking = new Booking(null, "", "", "", "", "");
        }

        Booking.updateBookingData(
                booking,
                (String) roomComboBox.getSelectedItem(),
                (String) Room.getRoomNameToIdMap().get(roomComboBox.getSelectedItem()),
                customerName.getText(),
                (String) CheckInTimeSlotCombobox.getSelectedItem(),
                (String) CheckInYearCombobox.getSelectedItem(),
                (String) CheckInMonthCombobox.getSelectedItem(),
                (String) CheckInDateCombobox.getSelectedItem());

        if (isNew) {
            if (Booking.isRoomBooked(booking.getRoomId(), booking.getCheckIn(), booking.getTimeSlot())) {
                MaOptionPane.showMessageDialog(this, "มีคนจองห้องนี้ในเวลานี้เเล้ว");
                return;
            }

            Booking.postBooking(booking, logger);
        } else {
            if (Booking.isRoomBooked(booking.getRoomId(), booking.getCheckIn(), booking.getTimeSlot(),
                    booking.getId())) {
                MaOptionPane.showMessageDialog(this, "มีคนจองห้องนี้ในเวลานี้เเล้ว");
                return;
            }
            Booking.putBooking(booking, logger);
        }
        parent.updateRender();
        dispose();
    }// GEN-LAST:event_submitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public void updateRender() {
        Room.loadRooms(logger);
        roomComboBox.setList(Room.getRoomNamesList().toArray(new String[1]));
        CheckInDateCombobox.setList(TimeUtils.days);
        CheckInYearCombobox.setList(TimeUtils.years);

        String[] monthNames = new String[TimeUtils.months.length];
        for (int i = 0; i < TimeUtils.months.length; i++) {
            monthNames[i] = TimeUtils.monthMap.get(TimeUtils.months[i]);
        }
        CheckInMonthCombobox.setList(monthNames);
        CheckInTimeSlotCombobox.setList(Booking.time_slot_list.toArray(new String[0]));
        if (booking != null) {

            customerName.setText(booking.getCustomer());
            roomComboBox.setSelectedItem(booking.getRoom());

            // Parse check-in/check-out ISO string
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss.SSSX");
            OffsetDateTime checkIn = OffsetDateTime.parse(booking.getCheckIn(), formatter);
            CheckInYearCombobox.setSelectedItem(String.valueOf(checkIn.getYear()));
            CheckInMonthCombobox.setSelectedItem(TimeUtils.monthMap.get(String.valueOf(checkIn.getMonthValue())));
            CheckInDateCombobox.setSelectedItem(String.valueOf(checkIn.getDayOfMonth()));
            CheckInTimeSlotCombobox.setSelectedItem(booking.getTimeSlot());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.core.components.MaComboBox CheckInDateCombobox;
    private app.core.components.MaComboBox CheckInMonthCombobox;
    private app.core.components.MaComboBox CheckInTimeSlotCombobox;
    private app.core.components.MaComboBox CheckInYearCombobox;
    private app.core.components.MaTextField customerName;
    private app.core.components.MaComboBox maComboBox10;
    private app.core.components.MaComboBox maComboBox11;
    private app.core.components.MaComboBox maComboBox7;
    private app.core.components.MaComboBox maComboBox8;
    private app.core.components.MaComboBox maComboBox9;
    private app.core.components.MaLabel maLabel1;
    private app.core.components.MaLabel maLabel2;
    private app.core.components.MaLabel maLabel3;
    private app.core.components.MaLabel maLabel4;
    private app.core.components.MaLabel maLabel7;
    private app.core.components.MaComboBox roomComboBox;
    private app.core.components.MaButton submitBtn;
    // End of variables declaration//GEN-END:variables

}
