/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentation.payment.view;

/**
 *
 * @author poke
 */
import app.core.components.*;
import app.core.components.fonts.IBMPlexSansThaiFont;
import presentation.receipt.controller.Receipt;
import presentation.booking.controller.Booking;
import presentation.roomAndaccessory.controller.Accessory;
import presentation.roomAndaccessory.controller.Room;

import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.border.Border;
import presentation.payment.controller.Payment;

public class PaymentHistoryFrame extends MaInternalFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PaymentHistoryFrame.class.getName());
    private ArrayList<Payment> paymentList = new ArrayList<>();
    
    /**
     * Creates new form PaymentHistoryFrame
     */
    public PaymentHistoryFrame() {
        initComponents();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paymentTable = new app.core.components.MaTable();
        navLabel1 = new app.core.components.NavLabel();
        maLabel1 = new app.core.components.MaLabel();
        refreshButton = new app.core.components.RefreshButton();

        setTitle("ประวัติการโอน");

        navLabel1.setExtraText("ประวัติโอนเงิน");

        maLabel1.setText("ประวัติการโอนเงิน");
        maLabel1.setTextColor(Macolor.magreen);
        maLabel1.setFont(IBMPlexSansThaiFont.medium(16));

        refreshButton.setText("");
        refreshButton.setText(null);
        refreshButton.setBorderColor(Macolor.trans);
        refreshButton.setBackground(Macolor.trans);
        refreshButton.setForeground(Macolor.magreen);
        refreshButton.addActionListener(this::refreshButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(maLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(paymentTable, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(navLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(navLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(maLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(paymentTable, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        loadData();
    }//GEN-LAST:event_refreshButtonActionPerformed
     
    public void loadData() {
        Room.loadRooms(logger);
        Booking.loadBookings(logger);
        Payment.loadPayments(logger);
        paymentList.clear();

        ArrayList<String> columns = new ArrayList<>();
        columns.add("ลูกค้า");
        columns.add("ห้อง");
        columns.add("Time Slot");
        columns.add("ยอดรวม (บาท)");
        columns.add("วันที่จ่าย");
        columns.add("สถานะ");

        ArrayList<Object[]> rows = new ArrayList<>();
        for (Payment p : Payment.data.values()) {
            paymentList.add(p);

            Booking b = Booking.data.get(p.getBookingId());
            String customer = b != null ? b.getCustomer() : "-";
            String room     = b != null ? b.getRoom()     : "-";
            String timeSlot = b != null ? b.getTimeSlot() : "-";

            String paidAt = p.getPaidAt();
            if (paidAt != null && paidAt.length() >= 10) paidAt = paidAt.substring(0, 10);

            rows.add(new Object[]{
                customer,
                room,
                timeSlot,
                String.format("%.2f", p.getAmount()),
                paidAt,
                p.getStatus()
            });
        }
        paymentTable.updateView(columns, rows);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.core.components.MaLabel maLabel1;
    private app.core.components.NavLabel navLabel1;
    private app.core.components.MaTable paymentTable;
    private app.core.components.RefreshButton refreshButton;
    // End of variables declaration//GEN-END:variables
}
