/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app.ui;

/**
 *
 * @author poke
 */
import app.components.lib.MaFrame;
import app.components.lib.*;
import app.components.lib.MaTextField;
import app.components.fonts.IBMPlexSansThaiFont;
import app.lib.PocketBaseClient;
import app.lib.PocketBaseClient.PBResponse;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Image;
import java.awt.TextField;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.*;
import javax.swing.ImageIcon;
import app.lib.SessionManager;
import app.util.TimeUtils;
import java.time.Instant;
import java.time.ZoneId;
import java.time.ZoneOffset;
import java.util.Map;


public class BookingTableFrame extends MaFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BookingTableFrame.class.getName());

    private PocketBaseClient pb = SessionManager.pb;
    private PBResponse pbClient;

    /**
     * Creates new form BookingTable
     */
    public BookingTableFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navLabel1 = new app.components.dashboard.NavLabel();
        jTextField1 = new javax.swing.JTextField();
        dateLabel = new app.components.lib.MaLabel();
        maTable1 = new app.components.lib.MaTable();
        bookingCalendar = new app.components.dashboard.BookingCalendar();
        navLabel2 = new app.components.dashboard.NavLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ตารางการจอง");

        dateLabel.setText("** โปรดเลือกวันที่ **");

        maTable1.updateView( new ArrayList<>(), new ArrayList<>());

        navLabel2.setExtraText("ตารางการจอง");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bookingCalendar, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                            .addComponent(maTable1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(navLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(navLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bookingCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(maTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        bookingCalendar.addDateSelectionListener(this::bookingCalendar1ActionPerformed);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookingCalendar1ActionPerformed(LocalDate selectedDate) {
        System.out.println("User selected: " + "\t" + selectedDate);
        dateLabel.setText("ข้อมูลการจอง ณ วันที่ :" + selectedDate);

        String[] utcRange = TimeUtils.convertDateToUtcRange(selectedDate, ZoneId.of("Asia/Bangkok"));
        String startUtc = utcRange[0]; // e.g., "2026-03-20T17:00:00Z"
        String endUtc = utcRange[1]; // e.g., "2026-03-21T17:00:00Z"
        if (!pb.isAuthenticated()) {
            System.out.println(pb.getAuthToken());
            return;
        }
        String filter = "checkIn_time <= '" + endUtc + "' && checkOut_time >= '" + startUtc + "'";
        Map<String, String> params = Map.of("filter", filter);
        try {
            PBResponse res = pb.getRecords("java_book", params);

            if (!res.isOk()) {
                logger.warning("Failed to load bookings: " + res.getStatusCode());
                return;
            }

            ArrayList<String> columns = new ArrayList<>();
            columns.add("Room Name");
            columns.add("Customer Name");
            columns.add("Check In");
            columns.add("Check Out");

            ArrayList<Object[]> rows = new ArrayList<>();

            List<String> items = res.getItems();

            if (items.isEmpty()) {
                dateLabel.setText("ไม่มีคิวในวันนี้"); 
                rows.add(new Object[]{"-", "-", "-", "-"});
            }
        

        for (String item : items) {

            String customerName = PocketBaseClient.extractJsonString(item, "customer_name");
            String checkIn = PocketBaseClient.extractJsonString(item, "checkIn_time");
            String checkOut = PocketBaseClient.extractJsonString(item, "checkOut_time");
            String roomName = PocketBaseClient.extractJsonString(item, "room_name");

            rows.add(new Object[]{
                roomName,
                customerName,
                checkIn,
                checkOut
            });
        }

        maTable1.updateView(columns, rows);

    }
    catch (java.io.IOException | InterruptedException ex

    
        ) {
            logger.log(java.util.logging.Level.SEVERE, "Failed to load bookings", ex);
    }

}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new BookingTableFrame().setVisible(true));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.components.dashboard.BookingCalendar bookingCalendar;
    private app.components.lib.MaLabel dateLabel;
    private javax.swing.JTextField jTextField1;
    private app.components.lib.MaTable maTable1;
    private app.components.dashboard.NavLabel navLabel1;
    private app.components.dashboard.NavLabel navLabel2;
    // End of variables declaration//GEN-END:variables
}
