/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app.ui;

/**
 *
 * @author poke
 */
import app.components.lib.MaFrame;
import app.components.lib.*;
import app.components.lib.MaTextField;
import app.components.fonts.IBMPlexSansThaiFont;
import app.lib.PocketBaseClient;
import app.lib.PocketBaseClient.PBResponse;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Image;
import java.awt.TextField;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.*;
import javax.swing.ImageIcon;
public class BookingFrame extends MaFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BookingFrame.class.getName());

    /**
     * Creates new form BookingFrame
     */
    public BookingFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navLabel = new app.components.dashboard.NavLabel();
        navLabel.setExtraText("จัดการการจอง");
        maButton1 = new app.components.lib.MaButton();
        maTable1 = new app.components.lib.MaTable();
        maButton2 = new app.components.lib.MaButton();
        maButton3 = new app.components.lib.MaButton();
        maPanel1 = new app.components.lib.MaPanel();
        maScrollPane1 = new app.components.lib.MaScrollPane();
        maTextArea1 = new app.components.lib.MaTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("จัดการการจอง");

        maButton1.setBorderColor(Macolor.magreen);
        maButton1.setTextColor(Macolor.magreen);
        maButton1.setButtonColor(Color.white);
        maButton1.setArc(35);
        maButton1.setText("+ เพิ่มข้อมูล");
        maButton1.addActionListener(this::maButton1ActionPerformed);

        maButton2.setButtonColor(Color.white);
        maButton2.setBorderColor(Macolor.mablue);
        maButton2.setTextColor(Macolor.mablue);
        maButton2.setArc(35);
        maButton2.setText("เเก้ไขข้อมูลที่เลือก");
        maButton2.addActionListener(this::maButton2ActionPerformed);

        maButton3.setButtonColor(Color.white);
        maButton3.setBorderColor(Macolor.mared);
        maButton3.setTextColor(Macolor.mared);
        maButton3.setArc(35);
        maButton3.setText("ลบข้อมูลที่เลือก");
        maButton3.addActionListener(this::maButton3ActionPerformed);

        maPanel1.setBackground(Color.white);
        maPanel1.setBorderColor(Macolor.magreen);

        maScrollPane1.setScrollX(false);
        maScrollPane1.scrollToTop();

        maTextArea1.setColumns(20);
        maTextArea1.setRows(5);
        maTextArea1.setText("วิธีการใช้งาน\n** วิธีการเพิ่มข้อมูล**\n\nกดปุ่ม “+ เพิ่มข้อมูล”\n1. ระบบจะเปิดฟอร์มให้กรอกข้อมูล (ขึ้นอยู่กับการออกแบบระบบ)\n2.กรอกข้อมูลให้ครบในแต่ละคอลัมน์\n3.กดยืนยันเพื่อบันทึกข้อมูล\n4.ข้อมูลใหม่จะแสดงในตารางทันที\n\n*หมายเหตุ: ควรตรวจสอบความถูกต้องก่อนบันทึก\n\n\n** วิธีการลบข้อมูล **\n\n1.คลิกเลือกแถวข้อมูลที่ต้องการลบ\n2.กดปุ่ม “ลบข้อมูลที่เลือก”\n\n* คำเตือน: การลบข้อมูลไม่สามารถกู้คืนได้ ควรตรวจสอบก่อนลบทุกครั้ง");
        maTextArea1.setTextColor(Macolor.magreen);
        maTextArea1.setBackground(Color.white);
        maTextArea1.setFont(IBMPlexSansThaiFont.light(12f));
        maTextArea1.setEditable(false);
        maTextArea1.setCaretPosition(0);
        maScrollPane1.setViewportView(maTextArea1);

        javax.swing.GroupLayout maPanel1Layout = new javax.swing.GroupLayout(maPanel1);
        maPanel1.setLayout(maPanel1Layout);
        maPanel1Layout.setHorizontalGroup(
            maPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 256, Short.MAX_VALUE)
            .addGroup(maPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(maPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(maScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        maPanel1Layout.setVerticalGroup(
            maPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 364, Short.MAX_VALUE)
            .addGroup(maPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(maPanel1Layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(maScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(10, 10, 10)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(navLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(maPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(maTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(maButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(maButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(maButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(navLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void maButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maButton1ActionPerformed

    private void maButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maButton2ActionPerformed

    private void maButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BookingFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.components.lib.MaButton maButton1;
    private app.components.lib.MaButton maButton2;
    private app.components.lib.MaButton maButton3;
    private app.components.lib.MaPanel maPanel1;
    private app.components.lib.MaScrollPane maScrollPane1;
    private app.components.lib.MaTable maTable1;
    private app.components.lib.MaTextArea maTextArea1;
    private app.components.dashboard.NavLabel navLabel;
    // End of variables declaration//GEN-END:variables
}
