/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app.ui;

import app.components.lib.MaFrame;
//import app.components.*;
import app.components.fonts.IBMPlexSansThaiFont;
import app.components.lib.MaOptionPane;
import app.components.lib.Macolor;
import java.awt.Color;
import app.lib.PocketBaseClient;
import app.lib.PocketBaseClient.PBResponse;

/**
 *
 * @author poke
 */
public class SignInFrame extends MaFrame {
    
    private PocketBaseClient pb = new PocketBaseClient("https://studiodb.hostmy.photos");
    private PBResponse pbClient;
    {
        try {
            pbClient = pb.authWithPassword("_superusers", System.getenv("SUPERUSERS_USERNAME"), System.getenv("SUPERUSERS_PASSWORD"));
        } catch (java.io.IOException | InterruptedException ex) {
            logger.log(java.util.logging.Level.SEVERE, "Authentication error", ex);
            pbClient = null;
        }
    }
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SignInFrame.class.getName());

    /**
     * Creates new form DashboardFrameTEst
     */
    public SignInFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        maFrame1 = new app.components.lib.MaFrame();
        maFrame2 = new app.components.lib.MaFrame();
        maFrame3 = new app.components.lib.MaFrame();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        headerLabel = new app.components.lib.MaLabel();
        userLabel = new app.components.lib.MaLabel();
        descLabel = new app.components.lib.MaLabel();
        passLabel = new app.components.lib.MaLabel();
        username = new app.components.lib.MaTextField();
        username.setArc(20);
        username.setPadding(10);
        username.setColumns(20);
        username.setFieldColor(Color.white);
        username.setBorderSize(1);
        username.setBorderColor(Macolor.textgrey);
        loginBtn = new app.components.lib.MaButton();
        password = new app.components.lib.MaPasswordField();
        password.setArc(20);
        password.setPadding(10);
        password.setColumns(20);
        password.setFieldColor(Color.white);
        password.setBorderSize(1);
        password.setBorderColor(Macolor.textgrey);

        javax.swing.GroupLayout maFrame1Layout = new javax.swing.GroupLayout(maFrame1.getContentPane());
        maFrame1.getContentPane().setLayout(maFrame1Layout);
        maFrame1Layout.setHorizontalGroup(
            maFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        maFrame1Layout.setVerticalGroup(
            maFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout maFrame2Layout = new javax.swing.GroupLayout(maFrame2.getContentPane());
        maFrame2.getContentPane().setLayout(maFrame2Layout);
        maFrame2Layout.setHorizontalGroup(
            maFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        maFrame2Layout.setVerticalGroup(
            maFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout maFrame3Layout = new javax.swing.GroupLayout(maFrame3.getContentPane());
        maFrame3.getContentPane().setLayout(maFrame3Layout);
        maFrame3Layout.setHorizontalGroup(
            maFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        maFrame3Layout.setVerticalGroup(
            maFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("เข้าสู่ระบบ");

        jPanel1.setMinimumSize(new java.awt.Dimension(400, 500));
        jPanel1.setBackground(Macolor.seablue);
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 500));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0};
        jPanel1Layout.rowHeights = new int[] {0, 14, 0, 14, 0, 14, 0, 14, 0, 14, 0, 14, 0};
        jPanel1.setLayout(jPanel1Layout);

        jPanel3.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel1.add(jPanel3, gridBagConstraints);

        headerLabel.setText("./MA studio");
        headerLabel.setTextColor(Macolor.magreen);
        headerLabel.setFont(IBMPlexSansThaiFont.bold(36f));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(headerLabel, gridBagConstraints);

        userLabel.setText("ชื่อผู้ใช้ (username)");
        userLabel.setFont(IBMPlexSansThaiFont.medium(14f));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(userLabel, gridBagConstraints);

        descLabel.setText("โปรดเข้าสู่ระบบเพื่อใช้งาน");
        descLabel.setTextColor(Macolor.textgrey);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(descLabel, gridBagConstraints);

        passLabel.setText("รหัสผ่าน ( password )");
        passLabel.setFont(IBMPlexSansThaiFont.medium(14f));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(passLabel, gridBagConstraints);

        username.addActionListener(this::usernameActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(username, gridBagConstraints);

        loginBtn.setText("เข้าสู่ระบบ");
        loginBtn.setArc(20);
        loginBtn.setButtonColor(Macolor.magreen);
        loginBtn.addActionListener(this::loginBtnActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(loginBtn, gridBagConstraints);

        password.addActionListener(this::passwordActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(password, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == loginBtn) {

            String user = username.getText();
            String pass = new String(password.getPassword());

            String adminId = System.getenv("ADMIN_ID");
            PBResponse admin = null;
            try {
                admin = pb.getRecord("java_login", adminId);
            } catch (java.io.IOException | InterruptedException ex) {
                logger.log(java.util.logging.Level.SEVERE, "Error fetching admin record", ex);
                MaOptionPane.showMessageDialog(this, "เกิดข้อผิดพลาดระหว่างดึงข้อมูลผู้ดูแลระบบ");
            }

            if (user.equals(admin.getJsonString("username")) && pass.equals(admin.getJsonString("password"))) {

                MaOptionPane.showMessageDialog(this, "การเข้าสู่ระบบสำเร็จ");

//                dispose signIn Frame
                dispose();
                new DashboardFrame().setVisible(true);

            } else {

                MaOptionPane.showMessageDialog(this, "รหัสผ่านหรือชื่อผู้ใช้ไม่ถูกต้อง");

            }
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SignInFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.components.lib.MaLabel descLabel;
    private app.components.lib.MaLabel headerLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private app.components.lib.MaButton loginBtn;
    private app.components.lib.MaFrame maFrame1;
    private app.components.lib.MaFrame maFrame2;
    private app.components.lib.MaFrame maFrame3;
    private app.components.lib.MaLabel passLabel;
    private app.components.lib.MaPasswordField password;
    private app.components.lib.MaLabel userLabel;
    private app.components.lib.MaTextField username;
    // End of variables declaration//GEN-END:variables
}
