/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentation.editbookAccessory.view;

/**
 *
 * @author poke
 */

import app.MainFrame;
import app.core.components.NavLabel;
import app.core.components.MaComboBox;
import app.core.components.MaFrame;
import app.core.components.MaInternalFrame;
import app.core.components.MaList;
import app.core.components.MaTable;
import app.core.components.Macolor;
import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import presentation.booking.controller.Booking;
import presentation.booking.view.EditBookingFrame;
import presentation.roomAndaccessory.view.EditAccessoryFrame;
public class BookAccessoryFrame extends MaInternalFrame {

    /**
     * Creates new form EditBookAccessoryFrame
     */
    public BookAccessoryFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        maLabel1 = new app.core.components.MaLabel();
        navLabel1 = new app.core.components.NavLabel();
        maTable1 = new app.core.components.MaTable();
        maButton1 = new app.core.components.MaButton();

        navLabel1.setExtraText("จัดการอุปกรณ์เเต่ละการจอง");

        maButton1.setText("เเก้ไขอุปกรณ์ของการจอง");
        maButton1.setBorderColor(Macolor.magreen);
        maButton1.setTextColor(Macolor.magreen);
        maButton1.setButtonColor(Color.white);
        maButton1.setArc(35);
        maButton1.addActionListener(this::maButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(maButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(navLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(maLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addComponent(maTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(navLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(maTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(maButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void maButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maButton1ActionPerformed
        // TODO add your handling code here:
                int tableselectedRow = maTable1.getSelectedRow();
        System.out.println(tableselectedRow);
        if (tableselectedRow >= 0) {
            ArrayList<String> bookingKeys = new ArrayList<>(Booking.data.keySet());
            String key = bookingKeys.get(tableselectedRow);
            Booking updateBooking = Booking.data.get(key);
            updateBooking.getId();
            System.out.println(updateBooking.getId());
//            MainFrame.getInstance().openInternalFrame(new EditAccessoryFrame(updateBooking.getId(),this));
        }
    }//GEN-LAST:event_maButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.core.components.MaButton maButton1;
    private app.core.components.MaLabel maLabel1;
    private app.core.components.MaTable maTable1;
    private app.core.components.NavLabel navLabel1;
    // End of variables declaration//GEN-END:variables
}
