/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentation.editbookAccessory.view;

/**
 *
 * @author poke
 */
public class EditBookAccessoryFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form EditBookAccessoryFrame
     */
    public EditBookAccessoryFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        maScrollPane1 = new app.core.components.MaScrollPane();
        maPanel1 = new app.core.components.MaPanel();
        maLabel1 = new app.core.components.MaLabel();

        maLabel1.setText("การจอง :");

        javax.swing.GroupLayout maPanel1Layout = new javax.swing.GroupLayout(maPanel1);
        maPanel1.setLayout(maPanel1Layout);
        maPanel1Layout.setHorizontalGroup(
            maPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(maLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(376, Short.MAX_VALUE))
        );
        maPanel1Layout.setVerticalGroup(
            maPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(maLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(374, Short.MAX_VALUE))
        );

        maScrollPane1.setViewportView(maPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(maScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(maScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.core.components.MaLabel maLabel1;
    private app.core.components.MaPanel maPanel1;
    private app.core.components.MaScrollPane maScrollPane1;
    // End of variables declaration//GEN-END:variables
}
